---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgi-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgi-deploy
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: tgi-deploy
    spec:
      containers:
      - env:
        - name: http_proxy
          value: "http://proxy-dmz.intel.com:911"
        - name: https_proxy
          value: "http://proxy-dmz.intel.com:912"
        - name: shm-size
          value: {{ .Values.shm-size }}
        - name: model-id
          value: {{ .Values.model-id }}
        - name: disable-custom-kernels
          value: {{ .Values.disable-custom-kernels }}
        image: {{ .Values.image.tgi_deploy }}
        name: tgi-deploy-demo
        volumeMounts:
        - mountPath: /data
          name: model-volume
        ports:
        - containerPort: 8180
        resources:
          limits:
            cpu: 56000m
            memory: 26Gi
          requests:
            cpu: 56000m
            memory: 26Gi
      serviceAccountName: default
      volumes:
      - name: model-volume
        hostPath:
          # directory location on host
          path: {{ .Values.volume.tgi_deploy  }}
          # this field is optional
          type: Directory
---
kind: Service
apiVersion: v1
metadata:
  name: tgi-deploy
spec:
  type: NodePort
  selector:
    app: tgi-deploy
  ports:
    - name: service
      port: 8180
      targetPort: 80
      nodePort: {{ .Values.nodePort.tgi_deploy }}
