---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-sum
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-sum
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: doc-sum
    spec:
      containers:
      - env:
        - name: http_proxy
          value: "http://proxy-dmz.intel.com:911"
        - name: https_proxy
          value: "http://proxy-dmz.intel.com:912"
        - name: HUGGINGFACEHUB_API_TOKEN
          value: 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
        - name: TGI_ENDPOINT
          value: tgi-deploy.default.svc.cluster.local:8180  
        image: intel/gen-ai-examples:document-summarize
        name: doc-sum
        command: ["nohup","python","app/server.py","&"] 
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 8000m
            memory: 26Gi
          requests:
            cpu: 8000m
            memory: 26Gi    
      serviceAccountName: default

---
kind: Service
apiVersion: v1
metadata:
  name: doc-sum
spec:
  type: NodePort
  selector:
    app: doc-sum
  ports:
    - name: http-service
      port: 8080
      targetPort: 8000
      nodePort: 30123         
